name: openmpi build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Checkout
      uses: actions/checkout@v2.4.2
      
    - name: Build and Push openmpi docker
      uses: docker/build-push-action@v3.1.1
      env:
        version: "4.1.4"
      with:
        context: .
        file: ./open-mpi/Dockerfile
        build-args: 
          OMPI_VERSION=${{ env.version }}
          OMPI_MAJOR_VERSION="v4.1"
        platforms: linux/amd64
        tags: julesg/openmpi:${{ env.version }}

